server:
  port: 9000
  contextPath: /

spring:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/springoauth
    username: springoauth
    password: springoauth

redis:
  datasource:
    host: localhost
    port: 6379

services:
  oauthServer: http://localhost:9000/
  oauthClient: http://localhost:9001/
