version: '2'

services:
  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.21
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  main-service-server:
    image: springio/main-service
    restart: unless-stopped
    depends_on:
      - kafka
    links:
      - kafka
    ports:
      - "8181:8181"

  user-service-server:
    image: springio/user-service
    restart: unless-stopped
    depends_on:
      - kafka
    links:
      - kafka
    ports:
      - "8282:8282"

  util-service-server:
      image: springio/util-service
      restart: unless-stopped
      depends_on:
        - kafka
      links:
        - kafka
      ports:
        - "8383:8383"

