version: '2'

services:
  zookeeper:
      image: zookeeper:3.4
      ports:
        - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.21
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper:zookeeper
    depends_on:
      - zookeeper

  kafka-producer:
    image: kafka-producer
    depends_on:
      - kafka
    links:
      - zookeeper
      - kafka

  kafka-consumer:
    image: kafka-consumer
    depends_on:
      - zookeeper
      - kafka
    links:
      - kafka
